name: Regression tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        pg: [9.6.17, 10.12, 11.7, 12.2]
        python: ['3.6', '3.7', '3.8']

    name: Run on ${{ matrix.python }} ${{ matrix.pg }}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Setup PostrgeSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ matrix.pg }}  # See https://hub.docker.com/_/postgres for available versions
      - run: python setup.py test
